# Generated by Django 5.1.3 on 2025-12-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
